/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.dbs.clconnbc.additionalNameapi.model;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;

@org.apache.avro.specific.AvroGenerated
public class AdditionalNameResponseAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3933547335434886454L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AdditionalNameResponseAvro\",\"namespace\":\"com.dbs.clconnbc.additionalNameapi.model\",\"fields\":[{\"name\":\"caseId\",\"type\":\"string\"},{\"name\":\"personId\",\"type\":\"string\"},{\"name\":\"correlationId\",\"type\":\"string\"},{\"name\":\"originator\",\"type\":\"string\"},{\"name\":\"additionalNames\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"AdditionalNamesAvro\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"type\",\"type\":\"string\"},{\"name\":\"screening\",\"type\":\"string\"},{\"name\":\"relationshipWithBO\",\"type\":\"string\"},{\"name\":\"BO\",\"type\":\"string\"},{\"name\":\"byGenAI\",\"type\":\"boolean\"}]}}},{\"name\":\"errorString\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AdditionalNameResponseAvro> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AdditionalNameResponseAvro> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AdditionalNameResponseAvro> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AdditionalNameResponseAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AdditionalNameResponseAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AdditionalNameResponseAvro to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AdditionalNameResponseAvro from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AdditionalNameResponseAvro instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AdditionalNameResponseAvro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private CharSequence caseId;
  private CharSequence personId;
  private CharSequence correlationId;
  private CharSequence originator;
  private java.util.List<AdditionalNamesAvro> additionalNames;
  private CharSequence errorString;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AdditionalNameResponseAvro() {}

  /**
   * All-args constructor.
   * @param caseId The new value for caseId
   * @param personId The new value for personId
   * @param correlationId The new value for correlationId
   * @param originator The new value for originator
   * @param additionalNames The new value for additionalNames
   * @param errorString The new value for errorString
   */
  public AdditionalNameResponseAvro(CharSequence caseId, CharSequence personId, CharSequence correlationId, CharSequence originator, java.util.List<AdditionalNamesAvro> additionalNames, CharSequence errorString) {
    this.caseId = caseId;
    this.personId = personId;
    this.correlationId = correlationId;
    this.originator = originator;
    this.additionalNames = additionalNames;
    this.errorString = errorString;
  }

  @Override
  public SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public Object get(int field$) {
    switch (field$) {
    case 0: return caseId;
    case 1: return personId;
    case 2: return correlationId;
    case 3: return originator;
    case 4: return additionalNames;
    case 5: return errorString;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: caseId = (CharSequence)value$; break;
    case 1: personId = (CharSequence)value$; break;
    case 2: correlationId = (CharSequence)value$; break;
    case 3: originator = (CharSequence)value$; break;
    case 4: additionalNames = (java.util.List<AdditionalNamesAvro>)value$; break;
    case 5: errorString = (CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'caseId' field.
   * @return The value of the 'caseId' field.
   */
  public CharSequence getCaseId() {
    return caseId;
  }


  /**
   * Sets the value of the 'caseId' field.
   * @param value the value to set.
   */
  public void setCaseId(CharSequence value) {
    this.caseId = value;
  }

  /**
   * Gets the value of the 'personId' field.
   * @return The value of the 'personId' field.
   */
  public CharSequence getPersonId() {
    return personId;
  }


  /**
   * Sets the value of the 'personId' field.
   * @param value the value to set.
   */
  public void setPersonId(CharSequence value) {
    this.personId = value;
  }

  /**
   * Gets the value of the 'correlationId' field.
   * @return The value of the 'correlationId' field.
   */
  public CharSequence getCorrelationId() {
    return correlationId;
  }


  /**
   * Sets the value of the 'correlationId' field.
   * @param value the value to set.
   */
  public void setCorrelationId(CharSequence value) {
    this.correlationId = value;
  }

  /**
   * Gets the value of the 'originator' field.
   * @return The value of the 'originator' field.
   */
  public CharSequence getOriginator() {
    return originator;
  }


  /**
   * Sets the value of the 'originator' field.
   * @param value the value to set.
   */
  public void setOriginator(CharSequence value) {
    this.originator = value;
  }

  /**
   * Gets the value of the 'additionalNames' field.
   * @return The value of the 'additionalNames' field.
   */
  public java.util.List<AdditionalNamesAvro> getAdditionalNames() {
    return additionalNames;
  }


  /**
   * Sets the value of the 'additionalNames' field.
   * @param value the value to set.
   */
  public void setAdditionalNames(java.util.List<AdditionalNamesAvro> value) {
    this.additionalNames = value;
  }

  /**
   * Gets the value of the 'errorString' field.
   * @return The value of the 'errorString' field.
   */
  public CharSequence getErrorString() {
    return errorString;
  }


  /**
   * Sets the value of the 'errorString' field.
   * @param value the value to set.
   */
  public void setErrorString(CharSequence value) {
    this.errorString = value;
  }

  /**
   * Creates a new AdditionalNameResponseAvro RecordBuilder.
   * @return A new AdditionalNameResponseAvro RecordBuilder
   */
  public static Builder newBuilder() {
    return new Builder();
  }

  /**
   * Creates a new AdditionalNameResponseAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AdditionalNameResponseAvro RecordBuilder
   */
  public static Builder newBuilder(Builder other) {
    if (other == null) {
      return new Builder();
    } else {
      return new Builder(other);
    }
  }

  /**
   * Creates a new AdditionalNameResponseAvro RecordBuilder by copying an existing AdditionalNameResponseAvro instance.
   * @param other The existing instance to copy.
   * @return A new AdditionalNameResponseAvro RecordBuilder
   */
  public static Builder newBuilder(AdditionalNameResponseAvro other) {
    if (other == null) {
      return new Builder();
    } else {
      return new Builder(other);
    }
  }

  /**
   * RecordBuilder for AdditionalNameResponseAvro instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AdditionalNameResponseAvro>
    implements org.apache.avro.data.RecordBuilder<AdditionalNameResponseAvro> {

    private CharSequence caseId;
    private CharSequence personId;
    private CharSequence correlationId;
    private CharSequence originator;
    private java.util.List<AdditionalNamesAvro> additionalNames;
    private CharSequence errorString;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.caseId)) {
        this.caseId = data().deepCopy(fields()[0].schema(), other.caseId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.personId)) {
        this.personId = data().deepCopy(fields()[1].schema(), other.personId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.correlationId)) {
        this.correlationId = data().deepCopy(fields()[2].schema(), other.correlationId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.originator)) {
        this.originator = data().deepCopy(fields()[3].schema(), other.originator);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.additionalNames)) {
        this.additionalNames = data().deepCopy(fields()[4].schema(), other.additionalNames);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.errorString)) {
        this.errorString = data().deepCopy(fields()[5].schema(), other.errorString);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing AdditionalNameResponseAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(AdditionalNameResponseAvro other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.caseId)) {
        this.caseId = data().deepCopy(fields()[0].schema(), other.caseId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.personId)) {
        this.personId = data().deepCopy(fields()[1].schema(), other.personId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.correlationId)) {
        this.correlationId = data().deepCopy(fields()[2].schema(), other.correlationId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.originator)) {
        this.originator = data().deepCopy(fields()[3].schema(), other.originator);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.additionalNames)) {
        this.additionalNames = data().deepCopy(fields()[4].schema(), other.additionalNames);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.errorString)) {
        this.errorString = data().deepCopy(fields()[5].schema(), other.errorString);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'caseId' field.
      * @return The value.
      */
    public CharSequence getCaseId() {
      return caseId;
    }


    /**
      * Sets the value of the 'caseId' field.
      * @param value The value of 'caseId'.
      * @return This builder.
      */
    public Builder setCaseId(CharSequence value) {
      validate(fields()[0], value);
      this.caseId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'caseId' field has been set.
      * @return True if the 'caseId' field has been set, false otherwise.
      */
    public boolean hasCaseId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'caseId' field.
      * @return This builder.
      */
    public Builder clearCaseId() {
      caseId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'personId' field.
      * @return The value.
      */
    public CharSequence getPersonId() {
      return personId;
    }


    /**
      * Sets the value of the 'personId' field.
      * @param value The value of 'personId'.
      * @return This builder.
      */
    public Builder setPersonId(CharSequence value) {
      validate(fields()[1], value);
      this.personId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'personId' field has been set.
      * @return True if the 'personId' field has been set, false otherwise.
      */
    public boolean hasPersonId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'personId' field.
      * @return This builder.
      */
    public Builder clearPersonId() {
      personId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'correlationId' field.
      * @return The value.
      */
    public CharSequence getCorrelationId() {
      return correlationId;
    }


    /**
      * Sets the value of the 'correlationId' field.
      * @param value The value of 'correlationId'.
      * @return This builder.
      */
    public Builder setCorrelationId(CharSequence value) {
      validate(fields()[2], value);
      this.correlationId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'correlationId' field has been set.
      * @return True if the 'correlationId' field has been set, false otherwise.
      */
    public boolean hasCorrelationId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'correlationId' field.
      * @return This builder.
      */
    public Builder clearCorrelationId() {
      correlationId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'originator' field.
      * @return The value.
      */
    public CharSequence getOriginator() {
      return originator;
    }


    /**
      * Sets the value of the 'originator' field.
      * @param value The value of 'originator'.
      * @return This builder.
      */
    public Builder setOriginator(CharSequence value) {
      validate(fields()[3], value);
      this.originator = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'originator' field has been set.
      * @return True if the 'originator' field has been set, false otherwise.
      */
    public boolean hasOriginator() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'originator' field.
      * @return This builder.
      */
    public Builder clearOriginator() {
      originator = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'additionalNames' field.
      * @return The value.
      */
    public java.util.List<AdditionalNamesAvro> getAdditionalNames() {
      return additionalNames;
    }


    /**
      * Sets the value of the 'additionalNames' field.
      * @param value The value of 'additionalNames'.
      * @return This builder.
      */
    public Builder setAdditionalNames(java.util.List<AdditionalNamesAvro> value) {
      validate(fields()[4], value);
      this.additionalNames = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'additionalNames' field has been set.
      * @return True if the 'additionalNames' field has been set, false otherwise.
      */
    public boolean hasAdditionalNames() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'additionalNames' field.
      * @return This builder.
      */
    public Builder clearAdditionalNames() {
      additionalNames = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'errorString' field.
      * @return The value.
      */
    public CharSequence getErrorString() {
      return errorString;
    }


    /**
      * Sets the value of the 'errorString' field.
      * @param value The value of 'errorString'.
      * @return This builder.
      */
    public Builder setErrorString(CharSequence value) {
      validate(fields()[5], value);
      this.errorString = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'errorString' field has been set.
      * @return True if the 'errorString' field has been set, false otherwise.
      */
    public boolean hasErrorString() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'errorString' field.
      * @return This builder.
      */
    public Builder clearErrorString() {
      errorString = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AdditionalNameResponseAvro build() {
      try {
        AdditionalNameResponseAvro record = new AdditionalNameResponseAvro();
        record.caseId = fieldSetFlags()[0] ? this.caseId : (CharSequence) defaultValue(fields()[0]);
        record.personId = fieldSetFlags()[1] ? this.personId : (CharSequence) defaultValue(fields()[1]);
        record.correlationId = fieldSetFlags()[2] ? this.correlationId : (CharSequence) defaultValue(fields()[2]);
        record.originator = fieldSetFlags()[3] ? this.originator : (CharSequence) defaultValue(fields()[3]);
        record.additionalNames = fieldSetFlags()[4] ? this.additionalNames : (java.util.List<AdditionalNamesAvro>) defaultValue(fields()[4]);
        record.errorString = fieldSetFlags()[5] ? this.errorString : (CharSequence) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AdditionalNameResponseAvro>
    WRITER$ = (org.apache.avro.io.DatumWriter<AdditionalNameResponseAvro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AdditionalNameResponseAvro>
    READER$ = (org.apache.avro.io.DatumReader<AdditionalNameResponseAvro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.caseId);

    out.writeString(this.personId);

    out.writeString(this.correlationId);

    out.writeString(this.originator);

    long size0 = this.additionalNames.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (AdditionalNamesAvro e0: this.additionalNames) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

    out.writeString(this.errorString);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.caseId = in.readString(this.caseId instanceof Utf8 ? (Utf8)this.caseId : null);

      this.personId = in.readString(this.personId instanceof Utf8 ? (Utf8)this.personId : null);

      this.correlationId = in.readString(this.correlationId instanceof Utf8 ? (Utf8)this.correlationId : null);

      this.originator = in.readString(this.originator instanceof Utf8 ? (Utf8)this.originator : null);

      long size0 = in.readArrayStart();
      java.util.List<AdditionalNamesAvro> a0 = this.additionalNames;
      if (a0 == null) {
        a0 = new SpecificData.Array<AdditionalNamesAvro>((int)size0, SCHEMA$.getField("additionalNames").schema());
        this.additionalNames = a0;
      } else a0.clear();
      SpecificData.Array<AdditionalNamesAvro> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<AdditionalNamesAvro>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          AdditionalNamesAvro e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new AdditionalNamesAvro();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

      this.errorString = in.readString(this.errorString instanceof Utf8 ? (Utf8)this.errorString : null);

    } else {
      for (int i = 0; i < 6; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.caseId = in.readString(this.caseId instanceof Utf8 ? (Utf8)this.caseId : null);
          break;

        case 1:
          this.personId = in.readString(this.personId instanceof Utf8 ? (Utf8)this.personId : null);
          break;

        case 2:
          this.correlationId = in.readString(this.correlationId instanceof Utf8 ? (Utf8)this.correlationId : null);
          break;

        case 3:
          this.originator = in.readString(this.originator instanceof Utf8 ? (Utf8)this.originator : null);
          break;

        case 4:
          long size0 = in.readArrayStart();
          java.util.List<AdditionalNamesAvro> a0 = this.additionalNames;
          if (a0 == null) {
            a0 = new SpecificData.Array<AdditionalNamesAvro>((int)size0, SCHEMA$.getField("additionalNames").schema());
            this.additionalNames = a0;
          } else a0.clear();
          SpecificData.Array<AdditionalNamesAvro> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<AdditionalNamesAvro>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              AdditionalNamesAvro e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new AdditionalNamesAvro();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        case 5:
          this.errorString = in.readString(this.errorString instanceof Utf8 ? (Utf8)this.errorString : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










