/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.dbs.clconnbc.additionalNameapi.model;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;

@org.apache.avro.specific.AvroGenerated
public class EmploymentAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6123802282936448245L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EmploymentAvro\",\"namespace\":\"com.dbs.clconnbc.additionalNameapi.model\",\"fields\":[{\"name\":\"employerName\",\"type\":\"string\"},{\"name\":\"pleaseElaborateOnSourceOfWealth\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<EmploymentAvro> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<EmploymentAvro> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<EmploymentAvro> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<EmploymentAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<EmploymentAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this EmploymentAvro to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a EmploymentAvro from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a EmploymentAvro instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static EmploymentAvro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private CharSequence employerName;
  private CharSequence pleaseElaborateOnSourceOfWealth;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public EmploymentAvro() {}

  /**
   * All-args constructor.
   * @param employerName The new value for employerName
   * @param pleaseElaborateOnSourceOfWealth The new value for pleaseElaborateOnSourceOfWealth
   */
  public EmploymentAvro(CharSequence employerName, CharSequence pleaseElaborateOnSourceOfWealth) {
    this.employerName = employerName;
    this.pleaseElaborateOnSourceOfWealth = pleaseElaborateOnSourceOfWealth;
  }

  @Override
  public SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public Object get(int field$) {
    switch (field$) {
    case 0: return employerName;
    case 1: return pleaseElaborateOnSourceOfWealth;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: employerName = (CharSequence)value$; break;
    case 1: pleaseElaborateOnSourceOfWealth = (CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'employerName' field.
   * @return The value of the 'employerName' field.
   */
  public CharSequence getEmployerName() {
    return employerName;
  }


  /**
   * Sets the value of the 'employerName' field.
   * @param value the value to set.
   */
  public void setEmployerName(CharSequence value) {
    this.employerName = value;
  }

  /**
   * Gets the value of the 'pleaseElaborateOnSourceOfWealth' field.
   * @return The value of the 'pleaseElaborateOnSourceOfWealth' field.
   */
  public CharSequence getPleaseElaborateOnSourceOfWealth() {
    return pleaseElaborateOnSourceOfWealth;
  }


  /**
   * Sets the value of the 'pleaseElaborateOnSourceOfWealth' field.
   * @param value the value to set.
   */
  public void setPleaseElaborateOnSourceOfWealth(CharSequence value) {
    this.pleaseElaborateOnSourceOfWealth = value;
  }

  /**
   * Creates a new EmploymentAvro RecordBuilder.
   * @return A new EmploymentAvro RecordBuilder
   */
  public static Builder newBuilder() {
    return new Builder();
  }

  /**
   * Creates a new EmploymentAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new EmploymentAvro RecordBuilder
   */
  public static Builder newBuilder(Builder other) {
    if (other == null) {
      return new Builder();
    } else {
      return new Builder(other);
    }
  }

  /**
   * Creates a new EmploymentAvro RecordBuilder by copying an existing EmploymentAvro instance.
   * @param other The existing instance to copy.
   * @return A new EmploymentAvro RecordBuilder
   */
  public static Builder newBuilder(EmploymentAvro other) {
    if (other == null) {
      return new Builder();
    } else {
      return new Builder(other);
    }
  }

  /**
   * RecordBuilder for EmploymentAvro instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EmploymentAvro>
    implements org.apache.avro.data.RecordBuilder<EmploymentAvro> {

    private CharSequence employerName;
    private CharSequence pleaseElaborateOnSourceOfWealth;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.employerName)) {
        this.employerName = data().deepCopy(fields()[0].schema(), other.employerName);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.pleaseElaborateOnSourceOfWealth)) {
        this.pleaseElaborateOnSourceOfWealth = data().deepCopy(fields()[1].schema(), other.pleaseElaborateOnSourceOfWealth);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing EmploymentAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(EmploymentAvro other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.employerName)) {
        this.employerName = data().deepCopy(fields()[0].schema(), other.employerName);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.pleaseElaborateOnSourceOfWealth)) {
        this.pleaseElaborateOnSourceOfWealth = data().deepCopy(fields()[1].schema(), other.pleaseElaborateOnSourceOfWealth);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'employerName' field.
      * @return The value.
      */
    public CharSequence getEmployerName() {
      return employerName;
    }


    /**
      * Sets the value of the 'employerName' field.
      * @param value The value of 'employerName'.
      * @return This builder.
      */
    public Builder setEmployerName(CharSequence value) {
      validate(fields()[0], value);
      this.employerName = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'employerName' field has been set.
      * @return True if the 'employerName' field has been set, false otherwise.
      */
    public boolean hasEmployerName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'employerName' field.
      * @return This builder.
      */
    public Builder clearEmployerName() {
      employerName = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'pleaseElaborateOnSourceOfWealth' field.
      * @return The value.
      */
    public CharSequence getPleaseElaborateOnSourceOfWealth() {
      return pleaseElaborateOnSourceOfWealth;
    }


    /**
      * Sets the value of the 'pleaseElaborateOnSourceOfWealth' field.
      * @param value The value of 'pleaseElaborateOnSourceOfWealth'.
      * @return This builder.
      */
    public Builder setPleaseElaborateOnSourceOfWealth(CharSequence value) {
      validate(fields()[1], value);
      this.pleaseElaborateOnSourceOfWealth = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'pleaseElaborateOnSourceOfWealth' field has been set.
      * @return True if the 'pleaseElaborateOnSourceOfWealth' field has been set, false otherwise.
      */
    public boolean hasPleaseElaborateOnSourceOfWealth() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'pleaseElaborateOnSourceOfWealth' field.
      * @return This builder.
      */
    public Builder clearPleaseElaborateOnSourceOfWealth() {
      pleaseElaborateOnSourceOfWealth = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public EmploymentAvro build() {
      try {
        EmploymentAvro record = new EmploymentAvro();
        record.employerName = fieldSetFlags()[0] ? this.employerName : (CharSequence) defaultValue(fields()[0]);
        record.pleaseElaborateOnSourceOfWealth = fieldSetFlags()[1] ? this.pleaseElaborateOnSourceOfWealth : (CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<EmploymentAvro>
    WRITER$ = (org.apache.avro.io.DatumWriter<EmploymentAvro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<EmploymentAvro>
    READER$ = (org.apache.avro.io.DatumReader<EmploymentAvro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.employerName);

    out.writeString(this.pleaseElaborateOnSourceOfWealth);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.employerName = in.readString(this.employerName instanceof Utf8 ? (Utf8)this.employerName : null);

      this.pleaseElaborateOnSourceOfWealth = in.readString(this.pleaseElaborateOnSourceOfWealth instanceof Utf8 ? (Utf8)this.pleaseElaborateOnSourceOfWealth : null);

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.employerName = in.readString(this.employerName instanceof Utf8 ? (Utf8)this.employerName : null);
          break;

        case 1:
          this.pleaseElaborateOnSourceOfWealth = in.readString(this.pleaseElaborateOnSourceOfWealth instanceof Utf8 ? (Utf8)this.pleaseElaborateOnSourceOfWealth : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










