/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.dbs.clconnbc.additionalNameapi.model;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;

@org.apache.avro.specific.AvroGenerated
public class OtherSOWAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2788348094533640693L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"OtherSOWAvro\",\"namespace\":\"com.dbs.clconnbc.additionalNameapi.model\",\"fields\":[{\"name\":\"pleaseElaborateOnSourceOfWealth\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<OtherSOWAvro> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<OtherSOWAvro> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<OtherSOWAvro> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<OtherSOWAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<OtherSOWAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this OtherSOWAvro to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a OtherSOWAvro from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a OtherSOWAvro instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static OtherSOWAvro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private CharSequence pleaseElaborateOnSourceOfWealth;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public OtherSOWAvro() {}

  /**
   * All-args constructor.
   * @param pleaseElaborateOnSourceOfWealth The new value for pleaseElaborateOnSourceOfWealth
   */
  public OtherSOWAvro(CharSequence pleaseElaborateOnSourceOfWealth) {
    this.pleaseElaborateOnSourceOfWealth = pleaseElaborateOnSourceOfWealth;
  }

  @Override
  public SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public Object get(int field$) {
    switch (field$) {
    case 0: return pleaseElaborateOnSourceOfWealth;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: pleaseElaborateOnSourceOfWealth = (CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'pleaseElaborateOnSourceOfWealth' field.
   * @return The value of the 'pleaseElaborateOnSourceOfWealth' field.
   */
  public CharSequence getPleaseElaborateOnSourceOfWealth() {
    return pleaseElaborateOnSourceOfWealth;
  }


  /**
   * Sets the value of the 'pleaseElaborateOnSourceOfWealth' field.
   * @param value the value to set.
   */
  public void setPleaseElaborateOnSourceOfWealth(CharSequence value) {
    this.pleaseElaborateOnSourceOfWealth = value;
  }

  /**
   * Creates a new OtherSOWAvro RecordBuilder.
   * @return A new OtherSOWAvro RecordBuilder
   */
  public static Builder newBuilder() {
    return new Builder();
  }

  /**
   * Creates a new OtherSOWAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new OtherSOWAvro RecordBuilder
   */
  public static Builder newBuilder(Builder other) {
    if (other == null) {
      return new Builder();
    } else {
      return new Builder(other);
    }
  }

  /**
   * Creates a new OtherSOWAvro RecordBuilder by copying an existing OtherSOWAvro instance.
   * @param other The existing instance to copy.
   * @return A new OtherSOWAvro RecordBuilder
   */
  public static Builder newBuilder(OtherSOWAvro other) {
    if (other == null) {
      return new Builder();
    } else {
      return new Builder(other);
    }
  }

  /**
   * RecordBuilder for OtherSOWAvro instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<OtherSOWAvro>
    implements org.apache.avro.data.RecordBuilder<OtherSOWAvro> {

    private CharSequence pleaseElaborateOnSourceOfWealth;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.pleaseElaborateOnSourceOfWealth)) {
        this.pleaseElaborateOnSourceOfWealth = data().deepCopy(fields()[0].schema(), other.pleaseElaborateOnSourceOfWealth);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing OtherSOWAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(OtherSOWAvro other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.pleaseElaborateOnSourceOfWealth)) {
        this.pleaseElaborateOnSourceOfWealth = data().deepCopy(fields()[0].schema(), other.pleaseElaborateOnSourceOfWealth);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'pleaseElaborateOnSourceOfWealth' field.
      * @return The value.
      */
    public CharSequence getPleaseElaborateOnSourceOfWealth() {
      return pleaseElaborateOnSourceOfWealth;
    }


    /**
      * Sets the value of the 'pleaseElaborateOnSourceOfWealth' field.
      * @param value The value of 'pleaseElaborateOnSourceOfWealth'.
      * @return This builder.
      */
    public Builder setPleaseElaborateOnSourceOfWealth(CharSequence value) {
      validate(fields()[0], value);
      this.pleaseElaborateOnSourceOfWealth = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'pleaseElaborateOnSourceOfWealth' field has been set.
      * @return True if the 'pleaseElaborateOnSourceOfWealth' field has been set, false otherwise.
      */
    public boolean hasPleaseElaborateOnSourceOfWealth() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'pleaseElaborateOnSourceOfWealth' field.
      * @return This builder.
      */
    public Builder clearPleaseElaborateOnSourceOfWealth() {
      pleaseElaborateOnSourceOfWealth = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public OtherSOWAvro build() {
      try {
        OtherSOWAvro record = new OtherSOWAvro();
        record.pleaseElaborateOnSourceOfWealth = fieldSetFlags()[0] ? this.pleaseElaborateOnSourceOfWealth : (CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<OtherSOWAvro>
    WRITER$ = (org.apache.avro.io.DatumWriter<OtherSOWAvro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<OtherSOWAvro>
    READER$ = (org.apache.avro.io.DatumReader<OtherSOWAvro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.pleaseElaborateOnSourceOfWealth);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.pleaseElaborateOnSourceOfWealth = in.readString(this.pleaseElaborateOnSourceOfWealth instanceof Utf8 ? (Utf8)this.pleaseElaborateOnSourceOfWealth : null);

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.pleaseElaborateOnSourceOfWealth = in.readString(this.pleaseElaborateOnSourceOfWealth instanceof Utf8 ? (Utf8)this.pleaseElaborateOnSourceOfWealth : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










