/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.imtf.dbs.namescreening.common.kafka.old;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class GenAiRequestHitUrlObject extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3792539827219934863L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"GenAiRequestHitUrlObject\",\"namespace\":\"com.imtf.dbs.namescreening.common.kafka.schema\",\"fields\":[{\"name\":\"hitId\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"hitUrl\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<GenAiRequestHitUrlObject> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<GenAiRequestHitUrlObject> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<GenAiRequestHitUrlObject> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<GenAiRequestHitUrlObject> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<GenAiRequestHitUrlObject> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this GenAiRequestHitUrlObject to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a GenAiRequestHitUrlObject from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a GenAiRequestHitUrlObject instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static GenAiRequestHitUrlObject fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private CharSequence hitId;
  private CharSequence hitUrl;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public GenAiRequestHitUrlObject() {}

  /**
   * All-args constructor.
   * @param hitId The new value for hitId
   * @param hitUrl The new value for hitUrl
   */
  public GenAiRequestHitUrlObject(CharSequence hitId, CharSequence hitUrl) {
    this.hitId = hitId;
    this.hitUrl = hitUrl;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public Object get(int field$) {
    switch (field$) {
    case 0: return hitId;
    case 1: return hitUrl;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: hitId = (CharSequence)value$; break;
    case 1: hitUrl = (CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'hitId' field.
   * @return The value of the 'hitId' field.
   */
  public CharSequence getHitId() {
    return hitId;
  }


  /**
   * Sets the value of the 'hitId' field.
   * @param value the value to set.
   */
  public void setHitId(CharSequence value) {
    this.hitId = value;
  }

  /**
   * Gets the value of the 'hitUrl' field.
   * @return The value of the 'hitUrl' field.
   */
  public CharSequence getHitUrl() {
    return hitUrl;
  }


  /**
   * Sets the value of the 'hitUrl' field.
   * @param value the value to set.
   */
  public void setHitUrl(CharSequence value) {
    this.hitUrl = value;
  }

  /**
   * Creates a new GenAiRequestHitUrlObject RecordBuilder.
   * @return A new GenAiRequestHitUrlObject RecordBuilder
   */
  public static Builder newBuilder() {
    return new Builder();
  }

  /**
   * Creates a new GenAiRequestHitUrlObject RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new GenAiRequestHitUrlObject RecordBuilder
   */
  public static Builder newBuilder(Builder other) {
    if (other == null) {
      return new Builder();
    } else {
      return new Builder(other);
    }
  }

  /**
   * Creates a new GenAiRequestHitUrlObject RecordBuilder by copying an existing GenAiRequestHitUrlObject instance.
   * @param other The existing instance to copy.
   * @return A new GenAiRequestHitUrlObject RecordBuilder
   */
  public static Builder newBuilder(GenAiRequestHitUrlObject other) {
    if (other == null) {
      return new Builder();
    } else {
      return new Builder(other);
    }
  }

  /**
   * RecordBuilder for GenAiRequestHitUrlObject instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<GenAiRequestHitUrlObject>
    implements org.apache.avro.data.RecordBuilder<GenAiRequestHitUrlObject> {

    private CharSequence hitId;
    private CharSequence hitUrl;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.hitId)) {
        this.hitId = data().deepCopy(fields()[0].schema(), other.hitId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.hitUrl)) {
        this.hitUrl = data().deepCopy(fields()[1].schema(), other.hitUrl);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing GenAiRequestHitUrlObject instance
     * @param other The existing instance to copy.
     */
    private Builder(GenAiRequestHitUrlObject other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.hitId)) {
        this.hitId = data().deepCopy(fields()[0].schema(), other.hitId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.hitUrl)) {
        this.hitUrl = data().deepCopy(fields()[1].schema(), other.hitUrl);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'hitId' field.
      * @return The value.
      */
    public CharSequence getHitId() {
      return hitId;
    }


    /**
      * Sets the value of the 'hitId' field.
      * @param value The value of 'hitId'.
      * @return This builder.
      */
    public Builder setHitId(CharSequence value) {
      validate(fields()[0], value);
      this.hitId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'hitId' field has been set.
      * @return True if the 'hitId' field has been set, false otherwise.
      */
    public boolean hasHitId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'hitId' field.
      * @return This builder.
      */
    public Builder clearHitId() {
      hitId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'hitUrl' field.
      * @return The value.
      */
    public CharSequence getHitUrl() {
      return hitUrl;
    }


    /**
      * Sets the value of the 'hitUrl' field.
      * @param value The value of 'hitUrl'.
      * @return This builder.
      */
    public Builder setHitUrl(CharSequence value) {
      validate(fields()[1], value);
      this.hitUrl = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'hitUrl' field has been set.
      * @return True if the 'hitUrl' field has been set, false otherwise.
      */
    public boolean hasHitUrl() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'hitUrl' field.
      * @return This builder.
      */
    public Builder clearHitUrl() {
      hitUrl = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public GenAiRequestHitUrlObject build() {
      try {
        GenAiRequestHitUrlObject record = new GenAiRequestHitUrlObject();
        record.hitId = fieldSetFlags()[0] ? this.hitId : (CharSequence) defaultValue(fields()[0]);
        record.hitUrl = fieldSetFlags()[1] ? this.hitUrl : (CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<GenAiRequestHitUrlObject>
    WRITER$ = (org.apache.avro.io.DatumWriter<GenAiRequestHitUrlObject>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<GenAiRequestHitUrlObject>
    READER$ = (org.apache.avro.io.DatumReader<GenAiRequestHitUrlObject>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.hitId == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.hitId);
    }

    if (this.hitUrl == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.hitUrl);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.hitId = null;
      } else {
        this.hitId = in.readString(this.hitId instanceof Utf8 ? (Utf8)this.hitId : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.hitUrl = null;
      } else {
        this.hitUrl = in.readString(this.hitUrl instanceof Utf8 ? (Utf8)this.hitUrl : null);
      }

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.hitId = null;
          } else {
            this.hitId = in.readString(this.hitId instanceof Utf8 ? (Utf8)this.hitId : null);
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.hitUrl = null;
          } else {
            this.hitUrl = in.readString(this.hitUrl instanceof Utf8 ? (Utf8)this.hitUrl : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










