/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.imtf.dbs.namescreening.common.kafka.old;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class GenAiRequestRecord extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8416103702804825326L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"GenAiRequestRecord\",\"namespace\":\"com.imtf.dbs.namescreening.common.kafka.schema\",\"fields\":[{\"name\":\"caseId\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"personId\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"riskCheckId\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"screeningHitId\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"screenedName\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"type\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"hitUrl\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"GenAiRequestHitUrlObject\",\"fields\":[{\"name\":\"hitId\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"hitUrl\",\"type\":[\"null\",\"string\"],\"default\":null}]}],\"default\":null},{\"name\":\"rmLocation\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"bookingCentre\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"additionalDetails\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"GenAiRequestAdditionalDetails\",\"fields\":[{\"name\":\"nationality\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"gender\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"dateOfBirth\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"identificationNumber\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"countryOfIncorporation\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"dateOfIncorporation\",\"type\":[\"null\",\"string\"],\"default\":null}]}],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<GenAiRequestRecord> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<GenAiRequestRecord> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<GenAiRequestRecord> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<GenAiRequestRecord> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<GenAiRequestRecord> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this GenAiRequestRecord to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a GenAiRequestRecord from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a GenAiRequestRecord instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static GenAiRequestRecord fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private CharSequence caseId;
  private CharSequence personId;
  private CharSequence riskCheckId;
  private CharSequence screeningHitId;
  private CharSequence screenedName;
  private CharSequence type;
  private GenAiRequestHitUrlObject hitUrl;
  private CharSequence rmLocation;
  private CharSequence bookingCentre;
  private GenAiRequestAdditionalDetails additionalDetails;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public GenAiRequestRecord() {}

  /**
   * All-args constructor.
   * @param caseId The new value for caseId
   * @param personId The new value for personId
   * @param riskCheckId The new value for riskCheckId
   * @param screeningHitId The new value for screeningHitId
   * @param screenedName The new value for screenedName
   * @param type The new value for type
   * @param hitUrl The new value for hitUrl
   * @param rmLocation The new value for rmLocation
   * @param bookingCentre The new value for bookingCentre
   * @param additionalDetails The new value for additionalDetails
   */
  public GenAiRequestRecord(CharSequence caseId, CharSequence personId, CharSequence riskCheckId, CharSequence screeningHitId, CharSequence screenedName, CharSequence type, GenAiRequestHitUrlObject hitUrl, CharSequence rmLocation, CharSequence bookingCentre, GenAiRequestAdditionalDetails additionalDetails) {
    this.caseId = caseId;
    this.personId = personId;
    this.riskCheckId = riskCheckId;
    this.screeningHitId = screeningHitId;
    this.screenedName = screenedName;
    this.type = type;
    this.hitUrl = hitUrl;
    this.rmLocation = rmLocation;
    this.bookingCentre = bookingCentre;
    this.additionalDetails = additionalDetails;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public Object get(int field$) {
    switch (field$) {
    case 0: return caseId;
    case 1: return personId;
    case 2: return riskCheckId;
    case 3: return screeningHitId;
    case 4: return screenedName;
    case 5: return type;
    case 6: return hitUrl;
    case 7: return rmLocation;
    case 8: return bookingCentre;
    case 9: return additionalDetails;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: caseId = (CharSequence)value$; break;
    case 1: personId = (CharSequence)value$; break;
    case 2: riskCheckId = (CharSequence)value$; break;
    case 3: screeningHitId = (CharSequence)value$; break;
    case 4: screenedName = (CharSequence)value$; break;
    case 5: type = (CharSequence)value$; break;
    case 6: hitUrl = (GenAiRequestHitUrlObject)value$; break;
    case 7: rmLocation = (CharSequence)value$; break;
    case 8: bookingCentre = (CharSequence)value$; break;
    case 9: additionalDetails = (GenAiRequestAdditionalDetails)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'caseId' field.
   * @return The value of the 'caseId' field.
   */
  public CharSequence getCaseId() {
    return caseId;
  }


  /**
   * Sets the value of the 'caseId' field.
   * @param value the value to set.
   */
  public void setCaseId(CharSequence value) {
    this.caseId = value;
  }

  /**
   * Gets the value of the 'personId' field.
   * @return The value of the 'personId' field.
   */
  public CharSequence getPersonId() {
    return personId;
  }


  /**
   * Sets the value of the 'personId' field.
   * @param value the value to set.
   */
  public void setPersonId(CharSequence value) {
    this.personId = value;
  }

  /**
   * Gets the value of the 'riskCheckId' field.
   * @return The value of the 'riskCheckId' field.
   */
  public CharSequence getRiskCheckId() {
    return riskCheckId;
  }


  /**
   * Sets the value of the 'riskCheckId' field.
   * @param value the value to set.
   */
  public void setRiskCheckId(CharSequence value) {
    this.riskCheckId = value;
  }

  /**
   * Gets the value of the 'screeningHitId' field.
   * @return The value of the 'screeningHitId' field.
   */
  public CharSequence getScreeningHitId() {
    return screeningHitId;
  }


  /**
   * Sets the value of the 'screeningHitId' field.
   * @param value the value to set.
   */
  public void setScreeningHitId(CharSequence value) {
    this.screeningHitId = value;
  }

  /**
   * Gets the value of the 'screenedName' field.
   * @return The value of the 'screenedName' field.
   */
  public CharSequence getScreenedName() {
    return screenedName;
  }


  /**
   * Sets the value of the 'screenedName' field.
   * @param value the value to set.
   */
  public void setScreenedName(CharSequence value) {
    this.screenedName = value;
  }

  /**
   * Gets the value of the 'type' field.
   * @return The value of the 'type' field.
   */
  public CharSequence getType() {
    return type;
  }


  /**
   * Sets the value of the 'type' field.
   * @param value the value to set.
   */
  public void setType(CharSequence value) {
    this.type = value;
  }

  /**
   * Gets the value of the 'hitUrl' field.
   * @return The value of the 'hitUrl' field.
   */
  public GenAiRequestHitUrlObject getHitUrl() {
    return hitUrl;
  }


  /**
   * Sets the value of the 'hitUrl' field.
   * @param value the value to set.
   */
  public void setHitUrl(GenAiRequestHitUrlObject value) {
    this.hitUrl = value;
  }

  /**
   * Gets the value of the 'rmLocation' field.
   * @return The value of the 'rmLocation' field.
   */
  public CharSequence getRmLocation() {
    return rmLocation;
  }


  /**
   * Sets the value of the 'rmLocation' field.
   * @param value the value to set.
   */
  public void setRmLocation(CharSequence value) {
    this.rmLocation = value;
  }

  /**
   * Gets the value of the 'bookingCentre' field.
   * @return The value of the 'bookingCentre' field.
   */
  public CharSequence getBookingCentre() {
    return bookingCentre;
  }


  /**
   * Sets the value of the 'bookingCentre' field.
   * @param value the value to set.
   */
  public void setBookingCentre(CharSequence value) {
    this.bookingCentre = value;
  }

  /**
   * Gets the value of the 'additionalDetails' field.
   * @return The value of the 'additionalDetails' field.
   */
  public GenAiRequestAdditionalDetails getAdditionalDetails() {
    return additionalDetails;
  }


  /**
   * Sets the value of the 'additionalDetails' field.
   * @param value the value to set.
   */
  public void setAdditionalDetails(GenAiRequestAdditionalDetails value) {
    this.additionalDetails = value;
  }

  /**
   * Creates a new GenAiRequestRecord RecordBuilder.
   * @return A new GenAiRequestRecord RecordBuilder
   */
  public static Builder newBuilder() {
    return new Builder();
  }

  /**
   * Creates a new GenAiRequestRecord RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new GenAiRequestRecord RecordBuilder
   */
  public static Builder newBuilder(Builder other) {
    if (other == null) {
      return new Builder();
    } else {
      return new Builder(other);
    }
  }

  /**
   * Creates a new GenAiRequestRecord RecordBuilder by copying an existing GenAiRequestRecord instance.
   * @param other The existing instance to copy.
   * @return A new GenAiRequestRecord RecordBuilder
   */
  public static Builder newBuilder(GenAiRequestRecord other) {
    if (other == null) {
      return new Builder();
    } else {
      return new Builder(other);
    }
  }

  /**
   * RecordBuilder for GenAiRequestRecord instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<GenAiRequestRecord>
    implements org.apache.avro.data.RecordBuilder<GenAiRequestRecord> {

    private CharSequence caseId;
    private CharSequence personId;
    private CharSequence riskCheckId;
    private CharSequence screeningHitId;
    private CharSequence screenedName;
    private CharSequence type;
    private GenAiRequestHitUrlObject hitUrl;
    private GenAiRequestHitUrlObject.Builder hitUrlBuilder;
    private CharSequence rmLocation;
    private CharSequence bookingCentre;
    private GenAiRequestAdditionalDetails additionalDetails;
    private GenAiRequestAdditionalDetails.Builder additionalDetailsBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.caseId)) {
        this.caseId = data().deepCopy(fields()[0].schema(), other.caseId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.personId)) {
        this.personId = data().deepCopy(fields()[1].schema(), other.personId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.riskCheckId)) {
        this.riskCheckId = data().deepCopy(fields()[2].schema(), other.riskCheckId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.screeningHitId)) {
        this.screeningHitId = data().deepCopy(fields()[3].schema(), other.screeningHitId);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.screenedName)) {
        this.screenedName = data().deepCopy(fields()[4].schema(), other.screenedName);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.type)) {
        this.type = data().deepCopy(fields()[5].schema(), other.type);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.hitUrl)) {
        this.hitUrl = data().deepCopy(fields()[6].schema(), other.hitUrl);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (other.hasHitUrlBuilder()) {
        this.hitUrlBuilder = GenAiRequestHitUrlObject.newBuilder(other.getHitUrlBuilder());
      }
      if (isValidValue(fields()[7], other.rmLocation)) {
        this.rmLocation = data().deepCopy(fields()[7].schema(), other.rmLocation);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.bookingCentre)) {
        this.bookingCentre = data().deepCopy(fields()[8].schema(), other.bookingCentre);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.additionalDetails)) {
        this.additionalDetails = data().deepCopy(fields()[9].schema(), other.additionalDetails);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (other.hasAdditionalDetailsBuilder()) {
        this.additionalDetailsBuilder = GenAiRequestAdditionalDetails.newBuilder(other.getAdditionalDetailsBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing GenAiRequestRecord instance
     * @param other The existing instance to copy.
     */
    private Builder(GenAiRequestRecord other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.caseId)) {
        this.caseId = data().deepCopy(fields()[0].schema(), other.caseId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.personId)) {
        this.personId = data().deepCopy(fields()[1].schema(), other.personId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.riskCheckId)) {
        this.riskCheckId = data().deepCopy(fields()[2].schema(), other.riskCheckId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.screeningHitId)) {
        this.screeningHitId = data().deepCopy(fields()[3].schema(), other.screeningHitId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.screenedName)) {
        this.screenedName = data().deepCopy(fields()[4].schema(), other.screenedName);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.type)) {
        this.type = data().deepCopy(fields()[5].schema(), other.type);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.hitUrl)) {
        this.hitUrl = data().deepCopy(fields()[6].schema(), other.hitUrl);
        fieldSetFlags()[6] = true;
      }
      this.hitUrlBuilder = null;
      if (isValidValue(fields()[7], other.rmLocation)) {
        this.rmLocation = data().deepCopy(fields()[7].schema(), other.rmLocation);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.bookingCentre)) {
        this.bookingCentre = data().deepCopy(fields()[8].schema(), other.bookingCentre);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.additionalDetails)) {
        this.additionalDetails = data().deepCopy(fields()[9].schema(), other.additionalDetails);
        fieldSetFlags()[9] = true;
      }
      this.additionalDetailsBuilder = null;
    }

    /**
      * Gets the value of the 'caseId' field.
      * @return The value.
      */
    public CharSequence getCaseId() {
      return caseId;
    }


    /**
      * Sets the value of the 'caseId' field.
      * @param value The value of 'caseId'.
      * @return This builder.
      */
    public Builder setCaseId(CharSequence value) {
      validate(fields()[0], value);
      this.caseId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'caseId' field has been set.
      * @return True if the 'caseId' field has been set, false otherwise.
      */
    public boolean hasCaseId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'caseId' field.
      * @return This builder.
      */
    public Builder clearCaseId() {
      caseId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'personId' field.
      * @return The value.
      */
    public CharSequence getPersonId() {
      return personId;
    }


    /**
      * Sets the value of the 'personId' field.
      * @param value The value of 'personId'.
      * @return This builder.
      */
    public Builder setPersonId(CharSequence value) {
      validate(fields()[1], value);
      this.personId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'personId' field has been set.
      * @return True if the 'personId' field has been set, false otherwise.
      */
    public boolean hasPersonId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'personId' field.
      * @return This builder.
      */
    public Builder clearPersonId() {
      personId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'riskCheckId' field.
      * @return The value.
      */
    public CharSequence getRiskCheckId() {
      return riskCheckId;
    }


    /**
      * Sets the value of the 'riskCheckId' field.
      * @param value The value of 'riskCheckId'.
      * @return This builder.
      */
    public Builder setRiskCheckId(CharSequence value) {
      validate(fields()[2], value);
      this.riskCheckId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'riskCheckId' field has been set.
      * @return True if the 'riskCheckId' field has been set, false otherwise.
      */
    public boolean hasRiskCheckId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'riskCheckId' field.
      * @return This builder.
      */
    public Builder clearRiskCheckId() {
      riskCheckId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'screeningHitId' field.
      * @return The value.
      */
    public CharSequence getScreeningHitId() {
      return screeningHitId;
    }


    /**
      * Sets the value of the 'screeningHitId' field.
      * @param value The value of 'screeningHitId'.
      * @return This builder.
      */
    public Builder setScreeningHitId(CharSequence value) {
      validate(fields()[3], value);
      this.screeningHitId = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'screeningHitId' field has been set.
      * @return True if the 'screeningHitId' field has been set, false otherwise.
      */
    public boolean hasScreeningHitId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'screeningHitId' field.
      * @return This builder.
      */
    public Builder clearScreeningHitId() {
      screeningHitId = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'screenedName' field.
      * @return The value.
      */
    public CharSequence getScreenedName() {
      return screenedName;
    }


    /**
      * Sets the value of the 'screenedName' field.
      * @param value The value of 'screenedName'.
      * @return This builder.
      */
    public Builder setScreenedName(CharSequence value) {
      validate(fields()[4], value);
      this.screenedName = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'screenedName' field has been set.
      * @return True if the 'screenedName' field has been set, false otherwise.
      */
    public boolean hasScreenedName() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'screenedName' field.
      * @return This builder.
      */
    public Builder clearScreenedName() {
      screenedName = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'type' field.
      * @return The value.
      */
    public CharSequence getType() {
      return type;
    }


    /**
      * Sets the value of the 'type' field.
      * @param value The value of 'type'.
      * @return This builder.
      */
    public Builder setType(CharSequence value) {
      validate(fields()[5], value);
      this.type = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'type' field has been set.
      * @return True if the 'type' field has been set, false otherwise.
      */
    public boolean hasType() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'type' field.
      * @return This builder.
      */
    public Builder clearType() {
      type = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'hitUrl' field.
      * @return The value.
      */
    public GenAiRequestHitUrlObject getHitUrl() {
      return hitUrl;
    }


    /**
      * Sets the value of the 'hitUrl' field.
      * @param value The value of 'hitUrl'.
      * @return This builder.
      */
    public Builder setHitUrl(GenAiRequestHitUrlObject value) {
      validate(fields()[6], value);
      this.hitUrlBuilder = null;
      this.hitUrl = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'hitUrl' field has been set.
      * @return True if the 'hitUrl' field has been set, false otherwise.
      */
    public boolean hasHitUrl() {
      return fieldSetFlags()[6];
    }

    /**
     * Gets the Builder instance for the 'hitUrl' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public GenAiRequestHitUrlObject.Builder getHitUrlBuilder() {
      if (hitUrlBuilder == null) {
        if (hasHitUrl()) {
          setHitUrlBuilder(GenAiRequestHitUrlObject.newBuilder(hitUrl));
        } else {
          setHitUrlBuilder(GenAiRequestHitUrlObject.newBuilder());
        }
      }
      return hitUrlBuilder;
    }

    /**
     * Sets the Builder instance for the 'hitUrl' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public Builder setHitUrlBuilder(GenAiRequestHitUrlObject.Builder value) {
      clearHitUrl();
      hitUrlBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'hitUrl' field has an active Builder instance
     * @return True if the 'hitUrl' field has an active Builder instance
     */
    public boolean hasHitUrlBuilder() {
      return hitUrlBuilder != null;
    }

    /**
      * Clears the value of the 'hitUrl' field.
      * @return This builder.
      */
    public Builder clearHitUrl() {
      hitUrl = null;
      hitUrlBuilder = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'rmLocation' field.
      * @return The value.
      */
    public CharSequence getRmLocation() {
      return rmLocation;
    }


    /**
      * Sets the value of the 'rmLocation' field.
      * @param value The value of 'rmLocation'.
      * @return This builder.
      */
    public Builder setRmLocation(CharSequence value) {
      validate(fields()[7], value);
      this.rmLocation = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'rmLocation' field has been set.
      * @return True if the 'rmLocation' field has been set, false otherwise.
      */
    public boolean hasRmLocation() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'rmLocation' field.
      * @return This builder.
      */
    public Builder clearRmLocation() {
      rmLocation = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'bookingCentre' field.
      * @return The value.
      */
    public CharSequence getBookingCentre() {
      return bookingCentre;
    }


    /**
      * Sets the value of the 'bookingCentre' field.
      * @param value The value of 'bookingCentre'.
      * @return This builder.
      */
    public Builder setBookingCentre(CharSequence value) {
      validate(fields()[8], value);
      this.bookingCentre = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'bookingCentre' field has been set.
      * @return True if the 'bookingCentre' field has been set, false otherwise.
      */
    public boolean hasBookingCentre() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'bookingCentre' field.
      * @return This builder.
      */
    public Builder clearBookingCentre() {
      bookingCentre = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'additionalDetails' field.
      * @return The value.
      */
    public GenAiRequestAdditionalDetails getAdditionalDetails() {
      return additionalDetails;
    }


    /**
      * Sets the value of the 'additionalDetails' field.
      * @param value The value of 'additionalDetails'.
      * @return This builder.
      */
    public Builder setAdditionalDetails(GenAiRequestAdditionalDetails value) {
      validate(fields()[9], value);
      this.additionalDetailsBuilder = null;
      this.additionalDetails = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'additionalDetails' field has been set.
      * @return True if the 'additionalDetails' field has been set, false otherwise.
      */
    public boolean hasAdditionalDetails() {
      return fieldSetFlags()[9];
    }

    /**
     * Gets the Builder instance for the 'additionalDetails' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public GenAiRequestAdditionalDetails.Builder getAdditionalDetailsBuilder() {
      if (additionalDetailsBuilder == null) {
        if (hasAdditionalDetails()) {
          setAdditionalDetailsBuilder(GenAiRequestAdditionalDetails.newBuilder(additionalDetails));
        } else {
          setAdditionalDetailsBuilder(GenAiRequestAdditionalDetails.newBuilder());
        }
      }
      return additionalDetailsBuilder;
    }

    /**
     * Sets the Builder instance for the 'additionalDetails' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public Builder setAdditionalDetailsBuilder(GenAiRequestAdditionalDetails.Builder value) {
      clearAdditionalDetails();
      additionalDetailsBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'additionalDetails' field has an active Builder instance
     * @return True if the 'additionalDetails' field has an active Builder instance
     */
    public boolean hasAdditionalDetailsBuilder() {
      return additionalDetailsBuilder != null;
    }

    /**
      * Clears the value of the 'additionalDetails' field.
      * @return This builder.
      */
    public Builder clearAdditionalDetails() {
      additionalDetails = null;
      additionalDetailsBuilder = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public GenAiRequestRecord build() {
      try {
        GenAiRequestRecord record = new GenAiRequestRecord();
        record.caseId = fieldSetFlags()[0] ? this.caseId : (CharSequence) defaultValue(fields()[0]);
        record.personId = fieldSetFlags()[1] ? this.personId : (CharSequence) defaultValue(fields()[1]);
        record.riskCheckId = fieldSetFlags()[2] ? this.riskCheckId : (CharSequence) defaultValue(fields()[2]);
        record.screeningHitId = fieldSetFlags()[3] ? this.screeningHitId : (CharSequence) defaultValue(fields()[3]);
        record.screenedName = fieldSetFlags()[4] ? this.screenedName : (CharSequence) defaultValue(fields()[4]);
        record.type = fieldSetFlags()[5] ? this.type : (CharSequence) defaultValue(fields()[5]);
        if (hitUrlBuilder != null) {
          try {
            record.hitUrl = this.hitUrlBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("hitUrl"));
            throw e;
          }
        } else {
          record.hitUrl = fieldSetFlags()[6] ? this.hitUrl : (GenAiRequestHitUrlObject) defaultValue(fields()[6]);
        }
        record.rmLocation = fieldSetFlags()[7] ? this.rmLocation : (CharSequence) defaultValue(fields()[7]);
        record.bookingCentre = fieldSetFlags()[8] ? this.bookingCentre : (CharSequence) defaultValue(fields()[8]);
        if (additionalDetailsBuilder != null) {
          try {
            record.additionalDetails = this.additionalDetailsBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("additionalDetails"));
            throw e;
          }
        } else {
          record.additionalDetails = fieldSetFlags()[9] ? this.additionalDetails : (GenAiRequestAdditionalDetails) defaultValue(fields()[9]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<GenAiRequestRecord>
    WRITER$ = (org.apache.avro.io.DatumWriter<GenAiRequestRecord>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<GenAiRequestRecord>
    READER$ = (org.apache.avro.io.DatumReader<GenAiRequestRecord>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.caseId == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.caseId);
    }

    if (this.personId == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.personId);
    }

    if (this.riskCheckId == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.riskCheckId);
    }

    if (this.screeningHitId == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.screeningHitId);
    }

    if (this.screenedName == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.screenedName);
    }

    if (this.type == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.type);
    }

    if (this.hitUrl == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      this.hitUrl.customEncode(out);
    }

    if (this.rmLocation == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.rmLocation);
    }

    if (this.bookingCentre == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.bookingCentre);
    }

    if (this.additionalDetails == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      this.additionalDetails.customEncode(out);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.caseId = null;
      } else {
        this.caseId = in.readString(this.caseId instanceof Utf8 ? (Utf8)this.caseId : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.personId = null;
      } else {
        this.personId = in.readString(this.personId instanceof Utf8 ? (Utf8)this.personId : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.riskCheckId = null;
      } else {
        this.riskCheckId = in.readString(this.riskCheckId instanceof Utf8 ? (Utf8)this.riskCheckId : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.screeningHitId = null;
      } else {
        this.screeningHitId = in.readString(this.screeningHitId instanceof Utf8 ? (Utf8)this.screeningHitId : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.screenedName = null;
      } else {
        this.screenedName = in.readString(this.screenedName instanceof Utf8 ? (Utf8)this.screenedName : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.type = null;
      } else {
        this.type = in.readString(this.type instanceof Utf8 ? (Utf8)this.type : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.hitUrl = null;
      } else {
        if (this.hitUrl == null) {
          this.hitUrl = new GenAiRequestHitUrlObject();
        }
        this.hitUrl.customDecode(in);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.rmLocation = null;
      } else {
        this.rmLocation = in.readString(this.rmLocation instanceof Utf8 ? (Utf8)this.rmLocation : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.bookingCentre = null;
      } else {
        this.bookingCentre = in.readString(this.bookingCentre instanceof Utf8 ? (Utf8)this.bookingCentre : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.additionalDetails = null;
      } else {
        if (this.additionalDetails == null) {
          this.additionalDetails = new GenAiRequestAdditionalDetails();
        }
        this.additionalDetails.customDecode(in);
      }

    } else {
      for (int i = 0; i < 10; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.caseId = null;
          } else {
            this.caseId = in.readString(this.caseId instanceof Utf8 ? (Utf8)this.caseId : null);
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.personId = null;
          } else {
            this.personId = in.readString(this.personId instanceof Utf8 ? (Utf8)this.personId : null);
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.riskCheckId = null;
          } else {
            this.riskCheckId = in.readString(this.riskCheckId instanceof Utf8 ? (Utf8)this.riskCheckId : null);
          }
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.screeningHitId = null;
          } else {
            this.screeningHitId = in.readString(this.screeningHitId instanceof Utf8 ? (Utf8)this.screeningHitId : null);
          }
          break;

        case 4:
          if (in.readIndex() != 1) {
            in.readNull();
            this.screenedName = null;
          } else {
            this.screenedName = in.readString(this.screenedName instanceof Utf8 ? (Utf8)this.screenedName : null);
          }
          break;

        case 5:
          if (in.readIndex() != 1) {
            in.readNull();
            this.type = null;
          } else {
            this.type = in.readString(this.type instanceof Utf8 ? (Utf8)this.type : null);
          }
          break;

        case 6:
          if (in.readIndex() != 1) {
            in.readNull();
            this.hitUrl = null;
          } else {
            if (this.hitUrl == null) {
              this.hitUrl = new GenAiRequestHitUrlObject();
            }
            this.hitUrl.customDecode(in);
          }
          break;

        case 7:
          if (in.readIndex() != 1) {
            in.readNull();
            this.rmLocation = null;
          } else {
            this.rmLocation = in.readString(this.rmLocation instanceof Utf8 ? (Utf8)this.rmLocation : null);
          }
          break;

        case 8:
          if (in.readIndex() != 1) {
            in.readNull();
            this.bookingCentre = null;
          } else {
            this.bookingCentre = in.readString(this.bookingCentre instanceof Utf8 ? (Utf8)this.bookingCentre : null);
          }
          break;

        case 9:
          if (in.readIndex() != 1) {
            in.readNull();
            this.additionalDetails = null;
          } else {
            if (this.additionalDetails == null) {
              this.additionalDetails = new GenAiRequestAdditionalDetails();
            }
            this.additionalDetails.customDecode(in);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










